language:
   - cpp

compiler: 
   - gcc

before_install:
  #install g++-4.8
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - if [ "$CXX" = "g++" ]; then sudo apt-get install g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
        
install:
   - sudo apt-get install libgtest-dev
   - cd /usr/src/gtest
   - sudo cmake CMakeLists.txt
   - sudo make
   - sudo cp *.a /usr/lib

script:
    - cd "${TRAVIS_BUILD_DIR}"
    - mkdir _builds
    - cd _builds
    - cmake ..
    - make
    - cd test
    - ctest
